version: '2'

volumes:
  nextcloud:
  db:

networks:
  web:
    external:
      name: dockertraefik_webgateway

services:
  db:
    image: mariadb
    restart: unless-stopped
    networks:
      - web
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nextcloud.docker.localhost"
